export enum TasksActionTypes {
  GET_TASK_BY_ID = "@TASKS/GET_TASKS_BY_ID",
  GET_TASKS_BY_USER_ID = "@TASKS/GET_TASKS_BY_USER_ID",
  ADD_TASK = "@TASKS/ADD_TASK",
  EDIT_TASK_BY_ID = "@TASKS/EDIT_TASK_BY_ID",
  DELETE_TASK_BY_ID = "@TASKS/DELETE_TASK_BY_ID",
  GET_TASK_COUNT_FOR_USER = "@TASKS/GET_TASK_COUNT_FOR_USER",
}
